# fly.toml app configuration file generated for makanwhere on 2023-07-04T22:38:10+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "makanwhere"
primary_region = "sin"

[build]
 
[deploy]
  release_command = "sh ./release.sh"

[env]
  PORT = "8000"
  USERNAME = "postgres"
  PASSWORD = "U3k1aJKz1wFxODk"
  DATABASE = "makanwhere-db"
  HOST = "makanwhere-db.internal"
  DIALECT = "postgres"
  NODE_ENV = "production"
  
  CORS_ORIGIN="http://localhost:3000"

  JWT_SECRET="2349283CA9DEAC413DE73E7B16532"
  JWT_EXPIRATION="60m"

  REFRESH_SECRET="A5BC85B5A62FDA9ACFB3A952F885C"
  REFRESH_EXPIRATION="7d"
  REFRESH_EXPIRATION_MS="604800000"
  REFRESH_MAX_AGE="7"

  RESET_EXPIRATION="1hour"
  RESET_EXPIRATION_MS="3600000"

  NODEMAILER_HOST="smtp.ethereal.email"
  NODEMAILER_PORT="587"

  GMAPS_API_KEY="AIzaSyDc8MetbdfF_ogjQyRTdSpw3YpOR0czkdg"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
